### PR TITLE
INHEART-155: Template - AuctionList 

### PR DESCRIPTION
**Pull request by BeataKula**
Edit - v5
- change star color
- change default background image  for auction
- change default auction image
image

Edit - v4
- adding underline to selected filter option
- add bottom padding
- code review comments
image
image

Edit - v3

- merge with develop
- sticky filter block
- some cosmetics changes

image

Edit - v2:
image

Some changes in AuctionList - part 1 - 
1. Previous version
2. Current version
3. Design version

image

### CODE REVIEW

**Comment by pmusialik-intive** [comment]
This is to redesign

**Comment by pmusialik-intive** [comment]
@zgr92 has an idea for that, it is shown on Figma - Booking inspiration

**Comment by BeataKula** [comment]
New changes after Redesign

**Review by zgr92 — APPROVED** [review]

**Review by KonradKarlinski — APPROVED** [review]

**Comment by KonradKarlinski** [comment]
It would be good to list these cosmetic changes

**Review by pmusialik-intive — APPROVED** [review]
If Misza is ok with their comments and some padding bottom at filter area added, then it's ok

**Pull request merged**
