### PR TITLE
INHEART-327 - 1.0.0 release

### PR DESCRIPTION
**Pull request by zgr92**
Release current state of our app with Auction List.

Tasks done:
[INHEART-102](https://tracker.intive.com/jira/browse/INHEART-102) [Auctions list](https://tracker.intive.com/jira/browse/INHEART-102) [Paweł Roguski](https://tracker.intive.com/jira/secure/ViewProfile.jspa?name=JIRAUSER26930) TEST
Major Sub-task [INHEART-155](https://tracker.intive.com/jira/browse/INHEART-155) [Template - AuctionList](https://tracker.intive.com/jira/browse/INHEART-155) [Beata Kula](https://tracker.intive.com/jira/secure/ViewProfile.jspa?name=JIRAUSER26945) TEST
Major Sub-task [INHEART-156](https://tracker.intive.com/jira/browse/INHEART-156) [Page - AuctionList](https://tracker.intive.com/jira/browse/INHEART-156) [Beata Kula](https://tracker.intive.com/jira/secure/ViewProfile.jspa?name=JIRAUSER26945) TEST
Major Sub-task [INHEART-210](https://tracker.intive.com/jira/browse/INHEART-210) [Reconsider the design of FilterBar and apply in the code](https://tracker.intive.com/jira/browse/INHEART-210) Unassigned DONE
Minor Story [INHEART-100](https://tracker.intive.com/jira/browse/INHEART-100) [Create auction module](https://tracker.intive.com/jira/browse/INHEART-100) [Paweł Roguski](https://tracker.intive.com/jira/secure/ViewProfile.jspa?name=JIRAUSER26930) DONE
Minor Sub-task [INHEART-145](https://tracker.intive.com/jira/browse/INHEART-145) [Molecule - DropdownAvatar](https://tracker.intive.com/jira/browse/INHEART-145) [Paweł Roguski](https://tracker.intive.com/jira/secure/ViewProfile.jspa?name=JIRAUSER26930) DONE
Minor Sub-task [INHEART-146](https://tracker.intive.com/jira/browse/INHEART-146) [Organism - Header](https://tracker.intive.com/jira/browse/INHEART-146) [Misza Pawlik](https://tracker.intive.com/jira/secure/ViewProfile.jspa?name=JIRAUSER24854) DONE
Minor Story [INHEART-169](https://tracker.intive.com/jira/browse/INHEART-169) [Flipper add to the project](https://tracker.intive.com/jira/browse/INHEART-169) [Przemysław Musialik](https://tracker.intive.com/jira/secure/ViewProfile.jspa?name=JIRAUSER26126) DONE
Minor Sub-task [INHEART-214](https://tracker.intive.com/jira/browse/INHEART-214) [Molecule - Dropdown avatar add Figma design](https://tracker.intive.com/jira/browse/INHEART-214) [Konrad Karliński](https://tracker.intive.com/jira/secure/ViewProfile.jspa?name=JIRAUSER24888) DONE
Low Story [INHEART-212](https://tracker.intive.com/jira/browse/INHEART-212) [[BUG] Fix tests with Icons](https://tracker.intive.com/jira/browse/INHEART-212) [Misza Pawlik](https://tracker.intive.com/jira/secure/ViewProfile.jspa?name=JIRAUSER24854) DONE

image

### CODE REVIEW

**Review by pmusialik-intive — COMMENTED** [review]
Shoud it be 0.1.0?

**Comment by konradhanus** [comment]
- [ ] - improve version
correct version is 1.0.0 :)

**Comment by konradhanus** [comment]
https://tracker.intive.com/jira/projects/INHEART/versions/32557

**Comment by konradhanus** [comment]
- [ ] - to description add stories which are included to this release




INHEART-102 | Auctions list | Paweł Roguski | TEST |   |  
  |   | INHEART-155 | Template - AuctionList | Beata Kula | TEST |   |  
  |   | INHEART-156 | Page - AuctionList | Beata Kula | TEST |   |  
  |   | INHEART-210 | Reconsider the design of FilterBar and apply in the code | Unassigned | DONE |   |  
  |   | INHEART-100 | Create auction module | Paweł Roguski | DONE |   |  
  |   | INHEART-145 | Molecule - DropdownAvatar | Paweł Roguski | DONE |   |  
  |   | INHEART-146 | Organism - Header | Misza Pawlik | DONE |   |  
  |   | INHEART-169 | Flipper add to the project | Przemysław Musialik | DONE |   |  
  |   | INHEART-214 | Molecule - Dropdown avatar add Figma design | Konrad Karliński | DONE |   |  
  |   | INHEART-212 | [BUG] Fix tests with Icons | Misza Pawlik | DONE

<br class="Apple-interchange-newline">[INHEART-102](https://tracker.intive.com/jira/browse/INHEART-102)	[Auctions list](https://tracker.intive.com/jira/browse/INHEART-102)	[Paweł Roguski](https://tracker.intive.com/jira/secure/ViewProfile.jspa?name=JIRAUSER26930)	TEST		
Major	Sub-task	[INHEART-155](https://tracker.intive.com/jira/browse/INHEART-155)	[Template - AuctionList](https://tracker.intive.com/jira/browse/INHEART-155)	[Beata Kula](https://tracker.intive.com/jira/secure/ViewProfile.jspa?name=JIRAUSER26945)	TEST		
Major	Sub-task	[INHEART-156](https://tracker.intive.com/jira/browse/INHEART-156)	[Page - AuctionList](https://tracker.intive.com/jira/browse/INHEART-156)	[Beata Kula](https://tracker.intive.com/jira/secure/ViewProfile.jspa?name=JIRAUSER26945)	TEST		
Major	Sub-task	[INHEART-210](https://tracker.intive.com/jira/browse/INHEART-210)	[Reconsider the design of FilterBar and apply in the code](https://tracker.intive.com/jira/browse/INHEART-210)	Unassigned	DONE		
Minor	Story	[INHEART-100](https://tracker.intive.com/jira/browse/INHEART-100)	[Create auction module](https://tracker.intive.com/jira/browse/INHEART-100)	[Paweł Roguski](https://tracker.intive.com/jira/secure/ViewProfile.jspa?name=JIRAUSER26930)	DONE		
Minor	Sub-task	[INHEART-145](https://tracker.intive.com/jira/browse/INHEART-145)	[Molecule - DropdownAvatar](https://tracker.intive.com/jira/browse/INHEART-145)	[Paweł Roguski](https://tracker.intive.com/jira/secure/ViewProfile.jspa?name=JIRAUSER26930)	DONE		
Minor	Sub-task	[INHEART-146](https://tracker.intive.com/jira/browse/INHEART-146)	[Organism - Header](https://tracker.intive.com/jira/browse/INHEART-146)	[Misza Pawlik](https://tracker.intive.com/jira/secure/ViewProfile.jspa?name=JIRAUSER24854)	DONE		
Minor	Story	[INHEART-169](https://tracker.intive.com/jira/browse/INHEART-169)	[Flipper add to the project](https://tracker.intive.com/jira/browse/INHEART-169)	[Przemysław Musialik](https://tracker.intive.com/jira/secure/ViewProfile.jspa?name=JIRAUSER26126)	DONE		
Minor	Sub-task	[INHEART-214](https://tracker.intive.com/jira/browse/INHEART-214)	[Molecule - Dropdown avatar add Figma design](https://tracker.intive.com/jira/browse/INHEART-214)	[Konrad Karliński](https://tracker.intive.com/jira/secure/ViewProfile.jspa?name=JIRAUSER24888)	DONE		
Low	Story	[INHEART-212](https://tracker.intive.com/jira/browse/INHEART-212)	[[BUG] Fix tests with Icons](https://tracker.intive.com/jira/browse/INHEART-212)	[Misza Pawlik](https://tracker.intive.com/jira/secure/ViewProfile.jspa?name=JIRAUSER24854)	DONE

**Review by pmusialik-intive — COMMENTED** [review]
image
After clicking on some item from filtering area, the text goes to the right (additional space added before text?) and the filtering area does not hide

**Review by pmusialik-intive — COMMENTED** [review]
image
The space between 'ends' and the rest is too big (and the colon is not necessary maybe? 😄)

**Review by KonradKarlinski — APPROVED** [review]

**Comment by KonradKarlinski** [comment]
- [ ]  Do not squash - remember.

**Comment by pawelroguski** [comment]
> image
> 
> The space between 'ends' and the rest is too big (and the colon is not necessary maybe? )

I think we can leave it as it is for now and fix it next time. I tried to find a quick fix, but I can't for now. It is not that important

**Review by konradhanus — APPROVED** [review]

**Review by BeataKula — APPROVED** [review]

**Review by pawelroguski — APPROVED** [review]

**Pull request merged**
