### PR TITLE
INHEART-397: Add my auctions page

### PR DESCRIPTION
**Pull request by captain-yossarian**
Add my auctions page

### CODE REVIEW

**Comment by pawelroguski** [comment]
In my opinion this approach You used is not good practise. It would be better to create one method (ie. findAll) and pass some parameters to it. Aauthor for example, where default value woud be null.

**Review by pawelroguski — COMMENTED** [review]
In my opinion this approach You used is not good practise. It would be better to create one method (ie. findAll) and pass some parameters to it. Aauthor for example, where default value woud be null.

**Comment by captain-yossarian** [comment]
> In my opinion this approach You used is not good practise. It would be better to create one method (ie. findAll) and pass some parameters to it. Aauthor for example, where default value woud be null.

@pawelroguski sure. We have separate task for BE, I made this change to make sure we have a correct UI

**Comment by pawelroguski** [comment]
> > In my opinion this approach You used is not good practise. It would be better to create one method (ie. findAll) and pass some parameters to it. Aauthor for example, where default value woud be null.
> 
> @pawelroguski sure. We have separate task for BE, I made this change to make sure we have a correct UI

Ohhh, i didn't know that ;) ! So You have approve from me ;)!

**Review by pawelroguski — APPROVED** [review]

**Pull request merged**
